engines:
  csslint:
    enabled: false
  scss-lint: 
    enabled: true
    checks:
      ImportantRule:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.vue"
  - "**.scss"
exclude_paths:
  - config/
  - test/
  - docs/
