language: node_js
sudo: false
node_js:
  - "8.4.0"
install:
  - npm install
script:
  - npm test && npm run build
before_install:
  - pip install --user codecov
after_success:
  - codecov --file test/unit/coverage/lcov.info --disable search
deploy:
  local_dir: 'docs'
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  slack: ninjaro:clZjvDamAByBYA004CYcYlH6
    on_success: always
    on_failure: always
  email:
    - theodoro.pelingan@gmail.com
