language: node_js
sudo: false
node_js:
  - "8.4.0"
install:
  - npm install
script:
  - npm test
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search